version: '3.7'

services:
  vexml:
    image: vexml:latest
    environment:
      PORT: 8080
    volumes:
      - ./dev:/vexml/dev
      - ./src:/vexml/src
    ports:
      - 8080:8080

  test:
    image: vexml:latest
    volumes:
      - ./dev:/vexml/dev
      - ./src:/vexml/src
    links:
      - vexml
