name: test
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: lint, check format, typecheck, then run tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install
        run: yarn install
      - name: lint
        run: yarn lint
      - name: check format
        run: yarn prettier . --check
      - name: typecheck
        run: yarn tsc --noEmit
      - name: test
        run: yarn test --ci
