name: test
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  premerge:
    name: run premerge code checks
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install
        run: npm ci
      - name: lint
        run: npm run lint
      - name: check format
        run: npm run format --check
      - name: typecheck
        run: npm run typecheck
      - name: test
        run: npm run test:ci
