name: typecheck
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  typecheck:
    name: typecheck src
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: compile
        run: yarn tsc --noEmit
